# SPDX-FileCopyrightText: 2019 The usbmon-tools Authors
#
# SPDX-License-Identifier: Apache-2.0

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
      - id: isort
        additional_dependencies:
          - toml
-   repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
    - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
-   repo: https://github.com/fsfe/reuse-tool
    rev: latest
    hooks:
    - id: reuse
